// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_repos_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserReposModel _$UserReposModelFromJson(Map<String, dynamic> json) =>
    UserReposModel(
      id: (json['id'] as num?)?.toInt(),
      nodeId: json['nodeId'] as String?,
      name: json['name'] as String?,
      fullName: json['fullName'] as String?,
      private: json['private'] as bool?,
      owner: json['owner'] == null
          ? null
          : UserReposOwnerModel.fromJson(json['owner'] as Map<String, dynamic>),
      htmlUrl: json['htmlUrl'] as String?,
      description: json['description'] as String?,
      fork: json['fork'] as bool?,
      url: json['url'] as String?,
      forksUrl: json['forksUrl'] as String?,
      keysUrl: json['keysUrl'] as String?,
      collaboratorsUrl: json['collaboratorsUrl'] as String?,
      teamsUrl: json['teamsUrl'] as String?,
      hooksUrl: json['hooksUrl'] as String?,
      issueEventsUrl: json['issueEventsUrl'] as String?,
      eventsUrl: json['eventsUrl'] as String?,
      assigneesUrl: json['assigneesUrl'] as String?,
      branchesUrl: json['branchesUrl'] as String?,
      tagsUrl: json['tagsUrl'] as String?,
      blobsUrl: json['blobsUrl'] as String?,
      gitTagsUrl: json['gitTagsUrl'] as String?,
      gitRefsUrl: json['gitRefsUrl'] as String?,
      treesUrl: json['treesUrl'] as String?,
      statusesUrl: json['statusesUrl'] as String?,
      languagesUrl: json['languagesUrl'] as String?,
      stargazersUrl: json['stargazersUrl'] as String?,
      contributorsUrl: json['contributorsUrl'] as String?,
      subscribersUrl: json['subscribersUrl'] as String?,
      subscriptionUrl: json['subscriptionUrl'] as String?,
      commitsUrl: json['commitsUrl'] as String?,
      gitCommitsUrl: json['gitCommitsUrl'] as String?,
      commentsUrl: json['commentsUrl'] as String?,
      issueCommentUrl: json['issueCommentUrl'] as String?,
      contentsUrl: json['contentsUrl'] as String?,
      compareUrl: json['compareUrl'] as String?,
      mergesUrl: json['mergesUrl'] as String?,
      archiveUrl: json['archiveUrl'] as String?,
      downloadsUrl: json['downloadsUrl'] as String?,
      issuesUrl: json['issuesUrl'] as String?,
      pullsUrl: json['pullsUrl'] as String?,
      milestonesUrl: json['milestonesUrl'] as String?,
      notificationsUrl: json['notificationsUrl'] as String?,
      labelsUrl: json['labelsUrl'] as String?,
      releasesUrl: json['releasesUrl'] as String?,
      deploymentsUrl: json['deploymentsUrl'] as String?,
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
      pushedAt: json['pushedAt'] as String?,
      gitUrl: json['gitUrl'] as String?,
      sshUrl: json['sshUrl'] as String?,
      cloneUrl: json['cloneUrl'] as String?,
      svnUrl: json['svnUrl'] as String?,
      homepage: json['homepage'],
      size: (json['size'] as num?)?.toInt(),
      stargazersCount: (json['stargazersCount'] as num?)?.toInt(),
      watchersCount: (json['watchersCount'] as num?)?.toInt(),
      language: json['language'] as String?,
      hasIssues: json['hasIssues'] as bool?,
      hasProjects: json['hasProjects'] as bool?,
      hasDownloads: json['hasDownloads'] as bool?,
      hasWiki: json['hasWiki'] as bool?,
      hasPages: json['hasPages'] as bool?,
      hasDiscussions: json['hasDiscussions'] as bool?,
      forksCount: (json['forksCount'] as num?)?.toInt(),
      mirrorUrl: json['mirrorUrl'],
      archived: json['archived'] as bool?,
      disabled: json['disabled'] as bool?,
      openIssuesCount: (json['openIssuesCount'] as num?)?.toInt(),
      license: json['license'],
      allowForking: json['allowForking'] as bool?,
      isTemplate: json['isTemplate'] as bool?,
      webCommitSignoffRequired: json['webCommitSignoffRequired'] as bool?,
      topics:
          (json['topics'] as List<dynamic>?)?.map((e) => e as String).toList(),
      visibility: json['visibility'] as String?,
      forks: (json['forks'] as num?)?.toInt(),
      openIssues: (json['openIssues'] as num?)?.toInt(),
      watchers: (json['watchers'] as num?)?.toInt(),
      defaultBranch: json['defaultBranch'] as String?,
    );

Map<String, dynamic> _$UserReposModelToJson(UserReposModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'nodeId': instance.nodeId,
      'name': instance.name,
      'fullName': instance.fullName,
      'private': instance.private,
      'owner': instance.owner,
      'htmlUrl': instance.htmlUrl,
      'description': instance.description,
      'fork': instance.fork,
      'url': instance.url,
      'forksUrl': instance.forksUrl,
      'keysUrl': instance.keysUrl,
      'collaboratorsUrl': instance.collaboratorsUrl,
      'teamsUrl': instance.teamsUrl,
      'hooksUrl': instance.hooksUrl,
      'issueEventsUrl': instance.issueEventsUrl,
      'eventsUrl': instance.eventsUrl,
      'assigneesUrl': instance.assigneesUrl,
      'branchesUrl': instance.branchesUrl,
      'tagsUrl': instance.tagsUrl,
      'blobsUrl': instance.blobsUrl,
      'gitTagsUrl': instance.gitTagsUrl,
      'gitRefsUrl': instance.gitRefsUrl,
      'treesUrl': instance.treesUrl,
      'statusesUrl': instance.statusesUrl,
      'languagesUrl': instance.languagesUrl,
      'stargazersUrl': instance.stargazersUrl,
      'contributorsUrl': instance.contributorsUrl,
      'subscribersUrl': instance.subscribersUrl,
      'subscriptionUrl': instance.subscriptionUrl,
      'commitsUrl': instance.commitsUrl,
      'gitCommitsUrl': instance.gitCommitsUrl,
      'commentsUrl': instance.commentsUrl,
      'issueCommentUrl': instance.issueCommentUrl,
      'contentsUrl': instance.contentsUrl,
      'compareUrl': instance.compareUrl,
      'mergesUrl': instance.mergesUrl,
      'archiveUrl': instance.archiveUrl,
      'downloadsUrl': instance.downloadsUrl,
      'issuesUrl': instance.issuesUrl,
      'pullsUrl': instance.pullsUrl,
      'milestonesUrl': instance.milestonesUrl,
      'notificationsUrl': instance.notificationsUrl,
      'labelsUrl': instance.labelsUrl,
      'releasesUrl': instance.releasesUrl,
      'deploymentsUrl': instance.deploymentsUrl,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'pushedAt': instance.pushedAt,
      'gitUrl': instance.gitUrl,
      'sshUrl': instance.sshUrl,
      'cloneUrl': instance.cloneUrl,
      'svnUrl': instance.svnUrl,
      'homepage': instance.homepage,
      'size': instance.size,
      'stargazersCount': instance.stargazersCount,
      'watchersCount': instance.watchersCount,
      'language': instance.language,
      'hasIssues': instance.hasIssues,
      'hasProjects': instance.hasProjects,
      'hasDownloads': instance.hasDownloads,
      'hasWiki': instance.hasWiki,
      'hasPages': instance.hasPages,
      'hasDiscussions': instance.hasDiscussions,
      'forksCount': instance.forksCount,
      'mirrorUrl': instance.mirrorUrl,
      'archived': instance.archived,
      'disabled': instance.disabled,
      'openIssuesCount': instance.openIssuesCount,
      'license': instance.license,
      'allowForking': instance.allowForking,
      'isTemplate': instance.isTemplate,
      'webCommitSignoffRequired': instance.webCommitSignoffRequired,
      'topics': instance.topics,
      'visibility': instance.visibility,
      'forks': instance.forks,
      'openIssues': instance.openIssues,
      'watchers': instance.watchers,
      'defaultBranch': instance.defaultBranch,
    };
